# In order for the config to work, you must stop the server to change the config.
min: 1
max: 100
# SECONDS between each new question
interval: 120
time-limit: 60
time-limit-exceeded: "&6Times up! The correct answer was &c%answer%&6."
question: "&6New Question: &c%x% %sign% %y% &6=&c ?"
answer: "&c%player% &6has solved the question in &c%time%s&6! The answer was: &c%answer%"